### ISSUE TITLE
Add full support for the `rules` key

### ISSUE THREAD

**Issue by gemfarmer** [18F/jekyll_frontmatter_tests#6]
Expected behavior:

We would expect that a configuration like so would check to make sure that items within an array were no-dash and lowercase. Rules would be configured in rules.yml and references in a specific schema.

```yml
tags:
  type: Array
  one_of: tags.yml
  rules: [no-dash, lowercase]
```

- check for valid date strings
  - check if date is today's date or later
  - if date is provided, ensure that it matches the filename
- check for valid image path

Actual behavior

It does nothing
